name: Deploy

on:
    pull_request:
        branches:
          - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

        - name: code checkout
          uses: actions/checkout@v2

        - name: install gcloud cli
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GOOGLE_PROJECT }}
            service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            export_default_credentials: true

        - name: build and push docker image
          env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          run:
            gcloud auth configure-docker southamerica-east1-docker.pkg.dev
            docker build -t southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/tv-shows-backend/tv-shows-backend-go:latest .
            docker push southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/tv-shows-backend/tv-shows-backend-go:latest
